services:
  body:
    # Sovrascriviamo SOLO il comando finale, dicendo a Docker 
    # di usare il tuo script invece di quello di Nadia
    command: ["python", "-u", "mock_body.py"]

  #Rimuoviamo l'helthcheck ereditato dal docker-compose originale,
  #perchè altrimenti Docker continuerebbe a segnalare il container
  #agv_body come "unhealthy" e quindi agv_body non partirebbe mai
    healthcheck:
      test: ["CMD", "true"]
      interval: 2s
      timeout: 2s
      retries: 1

  # Modifichiamo il Brain per dirgli di NON aspettare il body
  # In questo modo il Brain ignorerà il fatto che il body è "unhealthy" e partirà comunque
  brain:
    depends_on:
      - redis