services:
  # --- 1. MEMORIA E COMUNICAZIONE ---
  redis:
    image: redis:alpine
    container_name: agv_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - agv_net
    restart: always

  # --- 2. IL CERVELLO (Logic & BT) ---
  brain:
    build: ./src/brain
    container_name: agv_brain
    depends_on:
      - redis
    volumes:
      - ./src/brain:/app
      # MONTAGGIO ZMQ: Montiamo la cartella radice delle librerie esterne.
      # Questo rispetta l'importazione relativa della libreria CoppeliaSim.
      - ./external_libs:/usr/local/lib/python3.10/dist-packages/
    environment:
      - REDIS_HOST=agv_redis
      - PYTHONPATH=/app
    networks:
      - agv_net
    command: ["python", "-u", "main_brain.py"]

  # --- 3. IL CORPO (Hardware & Sim Bridge) ---
  body:
    build: ./src/body
    container_name: agv_body
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src/body:/app
      # MONTAGGIO ZMQ: Montiamo la cartella radice delle librerie esterne.
      #- ./external_libs:/usr/local/lib/python3.10/dist-packages/
    environment:
      - REDIS_HOST=agv_redis
      - COPPELIA_HOST=host.docker.internal # Indica al codice dove cercare Coppelia
      - PYTHONPATH=/app
    networks:
      - agv_net
    command: ["python", "-u", "mock_body.py"]

networks:
  agv_net:
    driver: bridge

volumes:
  redis_data: