%%{init: {"state": {"rankSpacing": 140, "nodeSpacing": 140}, "flowchart": {"curve": "basis"}}}%%
graph TD
    %% ==========================================
    %% DEFINIZIONE DEGLI STATI (Nodi)
    %% ==========================================
    START((Inizio))
    
    IDLE([IDLE])
    NODE([NODE_STATE])
    MANEUVER([MANEUVERING_STATE])
    REVERSE([REVERSING_STATE])
    FOLLOW([FOLLOWING_STATE])
    TARGET([TARGET_NODE_STATE])
    ERR([ERROR_STATE])

    %% ==========================================
    %% ARCHI USCENTI DA: START
    %% ==========================================
    START ---> IDLE

    %% ==========================================
    %% ARCHI USCENTI DA: IDLE
    %% ==========================================
    IDLE -->|c_t==STOP| IDLE
    IDLE --->|am_in_a_node| NODE
    IDLE --->|c_t==MOVE_TO & !am_in_a_node| FOLLOW

    %% ==========================================
    %% ARCHI USCENTI DA: NODE_STATE
    %% ==========================================
    NODE --->|c_t==MOVE_TO | MANEUVER
    NODE -.->|c_t==STOP| IDLE
    NODE -.->|c_t==PICKUP / DROP| ERR

    %% ==========================================
    %% ARCHI USCENTI DA: FOLLOWING_STATE
    %% ==========================================
    FOLLOW -->|c_t==MOVE_TO & !am_in_a_node| FOLLOW
    FOLLOW --->|am_in_a_node| NODE
    FOLLOW -.->|c_t==STOP| IDLE
    FOLLOW -.->|c_t==PICKUP / c_t==DROP| ERR

    %% ==========================================
    %% ARCHI USCENTI DA: MANEUVERING_STATE
    %% ==========================================
    MANEUVER -..->|manuuver_state==compleated| IDLE
    MANEUVER --->|next_node==target_node| REVERSE

    %% ==========================================
    %% ARCHI USCENTI DA: REVERSING_STATE
    %% ==========================================
    REVERSE --->|am_in_a_node & current_position==target_node| TARGET

    %% ==========================================
    %% ARCHI USCENTI DA: TARGET_NODE_STATE
    %% ==========================================
    TARGET -.->|c_t==STOP / c_t==PICKUP| MANEUVER

    linkStyle default stroke:#64748b,stroke-width:2.5px,stroke-linecap:round,stroke-linejoin:round,opacity:0.9;