graph TD
    %% DEFINIZIONE STILI
    classDef brain fill:#fff3e0,stroke:#e65100,stroke-width:2px;
    classDef body fill:#e1f5fe,stroke:#01579b,stroke-width:2px;
    classDef redis fill:#e8f5e9,stroke:#1b5e20,stroke-width:2px;
    classDef sim fill:#f3e5f5,stroke:#4a148c,stroke-width:2px,stroke-dasharray: 5 5;

    
        
    subgraph BRAIN_CONTAINER [Container BRAIN - Logic]
        BT[<b>Behavior Tree</b><br/>Manager]:::brain
        LOGIC[<b>Logic Controller</b><br/>Python Class]:::brain
    end

    subgraph REDIS_CONTAINER [Container REDIS]
        MESSAGER_SERVER[(<b>MESSAGER SERVER</b><br/>Key-Value & Pub/Sub)]:::redis
        BRAIN_MEMORY[(<b>BRAIN MEMORY</b><br/>Key-Value & Pub/Sub)]:::redis
        BODY_MEMORY[(<b>BODY MEMORY</b><br/>Key-Value & Pub/Sub)]:::redis
    end

    subgraph BODY_CONTAINER [Container BODY - Actuators & Sensors]
        subgraph SENSORS [SENSORS MODULE]
            GEN_SENS[<b>GENERIC SENSOR</b><br/>Class SensorObj<br/>Legge dai sensori e rielabora i dati, fa da <b>Perseption</b>]:::body
        end

        subgraph CONTROLLER [CONTROLLER MODULE]
            TASK_CONTROLLER[<b>TASK CONTROLLER</b><br/> legge dall'alto i comandi provenienti dal BRAIN]:::body
            PATH_CTR[<b>PATH CONTROLLER</b>]:::body
            DELIVERY_CTR[<b>DELIVERY CONTROLLER</b>]:::body
            
        end
        
        BRIDGE[<b>Coppelia Connector</b><br/>Singleton ZMQ]:::body
    
    end

    subgraph HOST_OS [CoppeliaSim]
        SIM_SENSOR(<b>Simulated Sensor</b><br/>Vision/Proximity/Laser):::sim
        SIM_ACTUATOR(<b>Simulated Actuator</b><br/>Joint/Wheel/Arm):::sim
    end

    %%-- FLUSSO DATI (PLAN)
    BT-->LOGIC
    LOGIC-->BT

    %% --- FLUSSO DATI (SENSE) ---
    SIM_SENSOR -- "1. Dati Grezzi (ZMQ)" --> BRIDGE
    BRIDGE --> GEN_SENS
    GEN_SENS -- "2. SET 'sensor_data'" --> BRAIN_MEMORY
    BRAIN_MEMORY -- "3. GET 'sensor_data'" --> LOGIC

    %% --- FLUSSO DATI (ACT) ---
    LOGIC -- "4. PUBLISH 'cmd_action'" --> MESSAGER_SERVER
    MESSAGER_SERVER -.-> |"5. SUBSCRIBE 'cmd_action'"| TASK_CONTROLLER

    TASK_CONTROLLER --> PATH_CTR
    TASK_CONTROLLER --> DELIVERY_CTR
    CTR_CINGOLO -->ACT_CINGOLO
    PATH_CTR -->LOW_CTR
    LOW_CTR -->LOW_CTR_LL
    LOW_CTR_LL -->GEN_ACT
    GEN_ACT --> BRIDGE
    ACT_CINGOLO --> BRIDGE
    BRIDGE -- "6. setTargetPosition (ZMQ)" --> SIM_ACTUATOR
    GEN_ACT -.-> |"Conferma dell'attuatore"|DB -.->BT
    ACT_CINGOLO -.-> |"Conferma dell'attuatore"|DB -.->BT

